SELECT PROJEKTAS_ID, NUM_PROGRAMUOTOJAS FROM	
	(SELECT PROJEKTAS_ID, COUNT(*) AS NUM_PROGRAMUOTOJAS
	FROM DARBUOTOJAS
	WHERE PAREIGOS = 'Programuotojas'
	GROUP BY PROJEKTAS_ID)
WHERE NUM_PROGRAMUOTOJAS > 1
