"""initial migration

Revision ID: 084a64c99f3d
Revises: 
Create Date: 2024-06-19 15:47:16.891677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084a64c99f3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Masina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modelis', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Masina', schema=None) as batch_op:
        batch_op.drop_column('modelis')

    # ### end Alembic commands ###
