"""miau sukuriame

Revision ID: d67a4bdf8e4c
Revises: 
Create Date: 2024-06-12 14:48:51.434013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd67a4bdf8e4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departamentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projektas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projektas', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Darbuotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('departamentas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamentas_id'], ['Departamentas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('darbuotojai_projektai',
    sa.Column('darbuotojas_id', sa.Integer(), nullable=True),
    sa.Column('projektas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['darbuotojas_id'], ['Darbuotojas.id'], ),
    sa.ForeignKeyConstraint(['projektas_id'], ['Projektas.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('darbuotojai_projektai')
    op.drop_table('Darbuotojas')
    op.drop_table('Projektas')
    op.drop_table('Departamentas')
    # ### end Alembic commands ###
