SELECT d1.VARDAS, d1.PAVARDE, d2.VARDAS as Vadovas_Vardas, p.PAVADINIMAS as Projekto_pavadinimas
FROM DARBUOTOJAS as d1
JOIN SKYRIUS as s ON d1.SKYRIUS_PAVADINIMAS = s.PAVADINIMAS
JOIN DARBUOTOJAS as d2 ON s.VADOVAS_ASMENSKODAS = d2.ASMENSKODAS
JOIN PROJEKTAS as p ON d1.PROJEKTAS_ID = p.ID